/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.PlayWave;
import java.awt.Color;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Random;
import javafx.scene.layout.Border;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author UTNG
 */
public class FrmPincipal extends javax.swing.JFrame {

    private JLabel[] tablero = new JLabel[16];
    private int[] datos = new int[16];
    private int pos1;
    private int pos2;
    private boolean banClick;//false=no seleccionada la imagen, true = imagen seleccionada
    private int tipo; //0 = LIBRE, 1= TRADICIONAL
    private int disponible; //CASILLA VACIA EN TIPO TRADICIONAL
    private JLabel lblTempo = new JLabel();
    private boolean banInicio; // true= ya inicio el juego, false = no ha iniciado el juego. 
    private FrmAcercaDe frmAcercaDe;

    /**
     * Creates new form FrmPincipal
     */
    public FrmPincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImage2 = new javax.swing.JLabel();
        lblImage3 = new javax.swing.JLabel();
        lblImage4 = new javax.swing.JLabel();
        lblImage1 = new javax.swing.JLabel();
        lblImage5 = new javax.swing.JLabel();
        lblImage6 = new javax.swing.JLabel();
        lblImage7 = new javax.swing.JLabel();
        lblImage8 = new javax.swing.JLabel();
        lblImage9 = new javax.swing.JLabel();
        lblImage10 = new javax.swing.JLabel();
        lblImage11 = new javax.swing.JLabel();
        lblImage12 = new javax.swing.JLabel();
        lblImage13 = new javax.swing.JLabel();
        lblImage14 = new javax.swing.JLabel();
        lblImage15 = new javax.swing.JLabel();
        lblImage16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbImagenes = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        btnMezclar = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rompecabezas v1");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a2.jpg"))); // NOI18N
        lblImage2.setText("jLabel1");
        lblImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage2MouseClicked(evt);
            }
        });

        lblImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a3.jpg"))); // NOI18N
        lblImage3.setText("jLabel1");
        lblImage3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage3MouseClicked(evt);
            }
        });

        lblImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a4.jpg"))); // NOI18N
        lblImage4.setText("jLabel1");
        lblImage4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage4MouseClicked(evt);
            }
        });

        lblImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a1.jpg"))); // NOI18N
        lblImage1.setText("jLabel1");
        lblImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage1MouseClicked(evt);
            }
        });

        lblImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a5.jpg"))); // NOI18N
        lblImage5.setText("jLabel1");
        lblImage5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage5MouseClicked(evt);
            }
        });

        lblImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a6.jpg"))); // NOI18N
        lblImage6.setText("jLabel1");
        lblImage6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage6MouseClicked(evt);
            }
        });

        lblImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a7.jpg"))); // NOI18N
        lblImage7.setText("jLabel1");
        lblImage7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage7MouseClicked(evt);
            }
        });

        lblImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a8.jpg"))); // NOI18N
        lblImage8.setText("jLabel1");
        lblImage8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage8MouseClicked(evt);
            }
        });

        lblImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a9.jpg"))); // NOI18N
        lblImage9.setText("jLabel1");
        lblImage9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage9MouseClicked(evt);
            }
        });

        lblImage10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10.jpg"))); // NOI18N
        lblImage10.setText("jLabel1");
        lblImage10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage10MouseClicked(evt);
            }
        });

        lblImage11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a11.jpg"))); // NOI18N
        lblImage11.setText("jLabel1");
        lblImage11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage11MouseClicked(evt);
            }
        });

        lblImage12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a12.jpg"))); // NOI18N
        lblImage12.setText("jLabel1");
        lblImage12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage12MouseClicked(evt);
            }
        });

        lblImage13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a13.jpg"))); // NOI18N
        lblImage13.setText("jLabel1");
        lblImage13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage13MouseClicked(evt);
            }
        });

        lblImage14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a14.jpg"))); // NOI18N
        lblImage14.setText("jLabel1");
        lblImage14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage14MouseClicked(evt);
            }
        });

        lblImage15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a15.jpg"))); // NOI18N
        lblImage15.setText("jLabel1");
        lblImage15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage15MouseClicked(evt);
            }
        });

        lblImage16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a16.jpg"))); // NOI18N
        lblImage16.setText("jLabel1");
        lblImage16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImage13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImage14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImage15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImage16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImage9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImage10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImage11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImage12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImage10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImage14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbImagenes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbImagenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Android", "Mario Bros", "Sombrerero", "Payaso", "Favorita", "Numeros", "Vegito", "Goku" }));
        cmbImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbImagenesActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Imagenes:");

        btnMezclar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMezclar.setText("Mezclar");
        btnMezclar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMezclarActionPerformed(evt);
            }
        });

        btnCreditos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCreditos.setText("Créditos");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Tipo:");

        cmbTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Tradicional", "Circular" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbImagenes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMezclar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel18)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMezclar)
                .addGap(18, 18, 18)
                .addComponent(btnCreditos)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tablero[0] = lblImage1;
        tablero[1] = lblImage2;
        tablero[2] = lblImage3;
        tablero[3] = lblImage4;
        tablero[4] = lblImage5;
        tablero[5] = lblImage6;
        tablero[6] = lblImage7;
        tablero[7] = lblImage8;
        tablero[8] = lblImage9;
        tablero[9] = lblImage10;
        tablero[10] = lblImage11;
        tablero[11] = lblImage12;
        tablero[12] = lblImage13;
        tablero[13] = lblImage14;
        tablero[14] = lblImage15;
        tablero[15] = lblImage16;
        for (int i = 0; i < 16; i++) {
            datos[i] = i;
        }
        sonidoFondo();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnMezclarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezclarActionPerformed
        // TODO add your handling code here:
        /**
         * Metodo que sirve para mezclar las imagenes
         */
        Random r1 = new Random();
        int x;
        if (tipo == 0) {
            for (int i = 0; i < 1000; i++) {
                x = r1.nextInt(16);
                seleccionar(x);
            }
        } else if (tipo == 1) {
            for (int i = 1; i <= 1000; i++) {
                x = r1.nextInt(16);
                mover(x);
            }
        }
        banInicio = true;
    }//GEN-LAST:event_btnMezclarActionPerformed

    private void lblImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage1MouseClicked
        // TODO add your handling code here:
       tirar(0);
    }//GEN-LAST:event_lblImage1MouseClicked

    private void lblImage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage2MouseClicked
        // TODO add your handling code here:
        tirar(1);
    }//GEN-LAST:event_lblImage2MouseClicked

    private void lblImage3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage3MouseClicked
        // TODO add your handling code here:
        tirar(2);
    }//GEN-LAST:event_lblImage3MouseClicked

    private void lblImage4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage4MouseClicked
        // TODO add your handling code here:
        tirar(3);
    }//GEN-LAST:event_lblImage4MouseClicked

    private void lblImage5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage5MouseClicked
        // TODO add your handling code here:
        tirar(4);
    }//GEN-LAST:event_lblImage5MouseClicked

    private void lblImage6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage6MouseClicked
        // TODO add your handling code here:
        tirar(5);
    }//GEN-LAST:event_lblImage6MouseClicked

    private void lblImage7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage7MouseClicked
        // TODO add your handling code here:
        tirar(6);
    }//GEN-LAST:event_lblImage7MouseClicked

    private void lblImage8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage8MouseClicked
        // TODO add your handling code here:
        tirar(7);
    }//GEN-LAST:event_lblImage8MouseClicked

    private void lblImage9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage9MouseClicked
        // TODO add your handling code here:
        tirar(8);
    }//GEN-LAST:event_lblImage9MouseClicked

    private void lblImage10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage10MouseClicked
        // TODO add your handling code here:
        tirar(9);
    }//GEN-LAST:event_lblImage10MouseClicked

    private void lblImage11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage11MouseClicked
        // TODO add your handling code here:
        tirar(10);
    }//GEN-LAST:event_lblImage11MouseClicked

    private void lblImage12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage12MouseClicked
        // TODO add your handling code here:
        tirar(11);
    }//GEN-LAST:event_lblImage12MouseClicked

    private void lblImage13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage13MouseClicked
        // TODO add your handling code here:
        tirar(12);
    }//GEN-LAST:event_lblImage13MouseClicked

    private void lblImage14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage14MouseClicked
        // TODO add your handling code here:
        tirar(13);
    }//GEN-LAST:event_lblImage14MouseClicked

    private void lblImage15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage15MouseClicked
        // TODO add your handling code here:
        tirar(14);
    }//GEN-LAST:event_lblImage15MouseClicked

    private void lblImage16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage16MouseClicked
        // TODO add your handling code here:
        tirar(15);
    }//GEN-LAST:event_lblImage16MouseClicked

    private void cmbImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImagenesActionPerformed
        // TODO add your handling code here:
        /**
         * Metodo que pone las imagenes dependiendo el tipo de categoria
         */
        banInicio = false;  //requiere mezclarse para iniciar
        disponible = 15;
        //se resetean los datos de las imagenes
        for (int i = 0; i < 16; i++) {
            datos[i] = i;
        }
        for (int i = 0; i < 16; i++) {
            tablero[i].setBorder(new LineBorder(Color.black, 1));
        }
        int op;
        op = cmbImagenes.getSelectedIndex();
        switch (op) {
            case 0:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/a1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/a2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/a3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/a4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/a5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/a6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/a7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/a8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/a9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/a10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/a11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/a12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/a13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/a14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/a15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/a16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/vacio.png")));
                }
                break;
            case 1:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/m1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/m2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/m3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/m4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/m5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/m6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/m7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/m8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/m9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/m10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/m11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/m12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/m13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/m14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/m15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/m16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/vacio.png")));
                }
                break;
            case 2:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/s1.png")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/s2.png")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/s3.png")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/s4.png")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/s5.png")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/s6.png")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/s7.png")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/s8.png")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/s9.png")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/s10.png")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/s11.png")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/s12.png")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/s13.png")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/s14.png")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/s15.png")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/s16.png")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/vacio.png")));
                }
                break;
            case 3:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/p1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/p2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/p3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/p4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/p5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/p6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/p7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/p8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/p9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/p10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/p11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/p12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/p13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/p14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/p15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/p16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/vacio.png")));
                }
                break;
            case 4:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/f1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/f2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/f3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/f4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/f5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/f6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/f7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/f8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/f9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/f10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/f11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/f12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/f13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/f14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/f15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/f16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/vacio.png")));
                }
                break;
            case 5:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/n1.png")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/n2.png")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/n3.png")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/n4.png")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/n5.png")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/n6.png")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/n7.png")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/n8.png")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/n9.png")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/n10.png")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/n11.png")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/n12.png")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/n13.png")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/n14.png")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/n15.png")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/n16.png")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/vacio.png")));
                }
                break;
            case 6:
               tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/g1.png")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/g2.png")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/g3.png")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/g4.png")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/g5.png")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/g6.png")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/g7.png")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/g8.png")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/g9.png")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/g10.png")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/g11.png")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/g12.png")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/g13.png")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/g14.png")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/g15.png")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/g16.png")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/vacio.png")));
                }
                break;
            case 7:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/go1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/go2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/go3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/go4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/go5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/go6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/go7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/go8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/go9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/go10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/go11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/go12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/go13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/go14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/go15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/go16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/vacio.png")));
                }

        }
    }//GEN-LAST:event_cmbImagenesActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
        /**
         * Metodo que funciona para cambiar de tipo de juego
         */
        tipo = cmbTipo.getSelectedIndex();
        if (tipo == 0) {//Libre
            ///
        } else if (tipo == 1) {//clasico
            lblImage16.setIcon(new ImageIcon(getClass().getResource("/imagenes/vacio.png")));
            disponible = 15;
        }
        this.cmbImagenesActionPerformed(null);
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        /**
         * Metodo que sirve para salir de la aplicacion
         */
        int res=JOptionPane.showConfirmDialog(null,"Estas seguro que quieres cerrar esta aplicación?");
        if(JOptionPane.OK_OPTION==res){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
        /**
         * Funcio que sirve para mandar llamar a otro formulario
         */
        frmAcercaDe=new FrmAcercaDe();
        frmAcercaDe.setVisible(true);
    }//GEN-LAST:event_btnCreditosActionPerformed
    /**
     * Metodo para intercambiar una casilla seleccionada con otra que este a su alrededor
     * @param pos
     * @return 
     */
    private boolean esValidoMov(int pos) {
        boolean salida = false;
        int dx; // fila disponible
        int dy; // columna disponible
        int posx; // fila de posicion a verificar
        int posy; //fila de posicion a verificar
        dx = disponible / 4;
        dy = disponible % 4;
        posx = pos / 4;
        posy = pos % 4;
        if (dx == posx) {//misma fila
            if (Math.abs(disponible - pos) == 1) {//para verificar que esta a distancia de 1
                salida = true;
            }
        }
        if (dy == posy) {//misma columna
            if (Math.abs(disponible - pos) == 4) {//para verificar que este a una distancia de 4 para la columna
                salida = true;
            }
        }
        return salida;
    }
    /**
     * Metodo que pinta la casilla selecciona
     * @param pos 
     */
    private void seleccionar(int pos) {
        if (!banClick) {  //primer click
            pos1 = pos;
            tablero[pos1].setBorder(javax.swing.BorderFactory.createLineBorder(
                    new java.awt.Color(255, 0, 0), 2));
            banClick = true;
        } else {
            pos2 = pos;
            tablero[pos1].setBorder(javax.swing.BorderFactory.createLineBorder(
                    new java.awt.Color(0, 0, 0), 2));
            banClick = false;
            intercambiar(pos1, pos2);
        }
    }
    /**
     * Intercambia imagenes de la posicion pos1 a la pos2
     * @param pos1
     * @param pos2 
     */
    private void intercambiar(int pos1, int pos2) {
        
        JLabel lblTempo = new JLabel();
        lblTempo.setIcon(tablero[pos1].getIcon());
        tablero[pos1].setIcon(tablero[pos2].getIcon());
        tablero[pos2].setIcon(lblTempo.getIcon());
        int tempo;
        tempo = datos[pos1];
        datos[pos1] = datos[pos2];
        datos[pos2] = tempo;
    }
    /**
     * Revisa que las imagenes esten en su lugar y decir que ya ganaste
     */
    private void revisar() {
        if (banInicio && !banClick && verificar()) {
            JOptionPane.showMessageDialog(this, "Ganaste!!");
            cmbTipo.setSelectedIndex(0);
            tipo = 0;
            for (int i = 0; i < 16; i++) {
                tablero[i].setBorder(null);
            }
            banInicio = false;
        }
    }
    /**
     * Verifica que esten en su lugar las imagenes
     * @return 
     */
    //verificar
    private boolean verificar() {
        for (int i = 0; i < 16; i++) {
            if (datos[i] != i) {
                return false;
            }
        }
        return true;
    }
    /**
     * Mueve la imagen seleccionada con otra imagen
     * @param pos 
     */
    private void mover(int pos) {
        if (banInicio) {
            if (tipo == 0) {
                seleccionar(pos);
            } else if (tipo == 1 || tipo == 2) {
                if (esValidoMov(pos)) {
                    intercambiar(pos, disponible);
                    disponible = pos; //<---------
                }
            }
        }
    }
    /**
     * Mover una linea en el modo tradicional
     * @param pos 
     */
    private void moverLinea(int pos) {
        if (banInicio) {
//            if (tipo == 2) {
//                lblTempo.setIcon(tablero[0].getIcon());
//                disponible = 0;
//                pos = 12;
//            }
            if (pos / 4 == disponible / 4) {//pertenece a la misma fila
                if (pos > disponible) {//esta a la derecha
                    for (int i = disponible + 1; i <= pos; i++) {
                        mover(i);
                    }
                } else {
                    for (int i = disponible - 1; i >= pos; i--) {
                        mover(i);
                    }
                }
            } else if (pos % 4 == disponible % 4) {//misma columna?
                if (pos > disponible) {//esta abajo?
                    for (int i = disponible + 4; i <= pos; i = i + 4) {
                        mover(i);
                    }
                } else {
                    for (int i = disponible - 4; i >= pos; i = i - 4) {
                        mover(i);
                    }
                }
            }
//            if(tipo==2){
//                tablero[12].set
//            }
        }
    }
    /**
     * Para poder mover la imagen
     * @param pos 
     */
    public void tirar(int pos){
        if(tipo==0){
           mover(pos);
       }else if(tipo==1){
           moverLinea(pos);
       }
        
        revisar();
    }
        /**
     * Metodo que hace que la musica se escuche.
     */    
    public void sonidoFondo() {
        try {
            PlayWave pw1;
            URL url = getClass().getResource("/media/KYLE.wav");
            pw1 = new PlayWave(url);
            pw1.start();
        } catch (URISyntaxException e) {
            System.out.println("Error en la URL!!");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnMezclar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbImagenes;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage10;
    private javax.swing.JLabel lblImage11;
    private javax.swing.JLabel lblImage12;
    private javax.swing.JLabel lblImage13;
    private javax.swing.JLabel lblImage14;
    private javax.swing.JLabel lblImage15;
    private javax.swing.JLabel lblImage16;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    private javax.swing.JLabel lblImage4;
    private javax.swing.JLabel lblImage5;
    private javax.swing.JLabel lblImage6;
    private javax.swing.JLabel lblImage7;
    private javax.swing.JLabel lblImage8;
    private javax.swing.JLabel lblImage9;
    // End of variables declaration//GEN-END:variables
}
