/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Gato;
import clases.PlayWave;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author ca_tics
 */
public class FrmIntro extends javax.swing.JFrame {
    private Gato g1;
    /**
     * Creates new form FrmIntro
     */
    public FrmIntro(Gato g1) {
        initComponents();
        this.g1= g1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJugador1 = new javax.swing.JTextField();
        txtJugador2 = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rbtnX1 = new javax.swing.JRadioButton();
        rbtnO1 = new javax.swing.JRadioButton();
        rbtnX2 = new javax.swing.JRadioButton();
        rbtnO2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego el Gato v1.0");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Juego del Gato");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Jugador #1:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Jugador #2:");

        txtJugador1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtJugador2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato_pics/gato.png"))); // NOI18N

        buttonGroup1.add(rbtnX1);
        rbtnX1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnX1.setSelected(true);
        rbtnX1.setText("X");
        rbtnX1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnX1ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbtnO1);
        rbtnO1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnO1.setText("O");
        rbtnO1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnO1ItemStateChanged(evt);
            }
        });

        buttonGroup2.add(rbtnX2);
        rbtnX2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnX2.setText("X");
        rbtnX2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnX2ItemStateChanged(evt);
            }
        });

        buttonGroup2.add(rbtnO2);
        rbtnO2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnO2.setSelected(true);
        rbtnO2.setText("O");
        rbtnO2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnO2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegresar)
                                    .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnX2)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtnO2))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnX1)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtnO1))
                                    .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnX1)
                    .addComponent(rbtnO1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnX2)
                    .addComponent(rbtnO2))
                .addGap(44, 44, 44)
                .addComponent(btnRegresar)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        /**
         * Funciona para regresar al Formulario principal, guardando los datos 
         * y al momento de regresar sonara una cancion.
         */
//        g1.setJugador1(txtJugador1.getText());
//        g1.setJugador2(txtJugador2.getText());
        String jugador1= txtJugador1.getText().trim();
        String jugador2= txtJugador2.getText().trim();
        if(rbtnX1.isSelected()){
            g1.setTiroJ1(1);
            //g1.setTiroJ2(2);
        }else{
            g1.setTiroJ1(2);
            //g1.setTiroJ2(1);
        }
        if(jugador1.length()>0&&jugador2.length()>0){
            g1.setJugador1(jugador1);
            g1.setJugador2(jugador2);
            this.setVisible(false);
           // sonidoFondo();
        }else{
            JOptionPane.showMessageDialog(this, "Datos incompletos!!");
        }
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void rbtnX1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnX1ItemStateChanged
        // TODO add your handling code here:
        /**
         * Sirve para seleccionar la figura con la que quieres jugar y al seleccionar
         * una automaticamente la otra se selecciona en la casilla contraria.
         */
        if(rbtnX1.isSelected()){
            rbtnX2.setSelected(false);
        }else{
            rbtnX2.setSelected(true);
        }
    }//GEN-LAST:event_rbtnX1ItemStateChanged

    private void rbtnX2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnX2ItemStateChanged
        // TODO add your handling code here:
        /**
         * Sirve para seleccionar la figura con la que quieres jugar y al seleccionar
         * una automaticamente la otra se selecciona en la casilla contraria.
         */
        if(rbtnX2.isSelected()){
            rbtnX1.setSelected(false);
        }else{
            rbtnX1.setSelected(true);
        }
    }//GEN-LAST:event_rbtnX2ItemStateChanged

    private void rbtnO1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnO1ItemStateChanged
        // TODO add your handling code here:
        /**
         * Sirve para seleccionar la figura con la que quieres jugar y al seleccionar
         * una automaticamente la otra se selecciona en la casilla contraria.
         */
        if(rbtnO1.isSelected()){
            rbtnO2.setSelected(false);
        }else{
            rbtnO2.setSelected(true);
        }
    }//GEN-LAST:event_rbtnO1ItemStateChanged

    private void rbtnO2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnO2ItemStateChanged
        // TODO add your handling code here:
        /**
         * Sirve para seleccionar la figura con la que quieres jugar y al seleccionar
         * una automaticamente la otra se selecciona en la casilla contraria.
         */
        if(rbtnO2.isSelected()){
            rbtnO1.setSelected(false);
        }else{
            rbtnO1.setSelected(true);
        }
    }//GEN-LAST:event_rbtnO2ItemStateChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmIntro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtnO1;
    private javax.swing.JRadioButton rbtnO2;
    private javax.swing.JRadioButton rbtnX1;
    private javax.swing.JRadioButton rbtnX2;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
